name: linked_text
description: >-
  A Flutter widget that renders text with interpolated tappable links using a
  simple template syntax.
version: 1.1.1
repository: https://github.com/pento/linked_text
topics:
  - text
  - links
  - rich-text
  - url-launcher
  - widget

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  hooks: ^1.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.3.2
